export const PROCESS_LCM4 = {
  pmApps: [
    {
      name: "nova-test-app1",
      dataSchemaVersion: "1.0.0",
      configSchemaVersion: "1.0.0",
      contextPath: "/nova-test",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-test-app2",
      dataSchemaVersion: "1.0.0",
      configSchemaVersion: "1.0.0",
      contextPath: "/nova-test2",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-test-app3",
      dataSchemaVersion: "1.0.0",
      configSchemaVersion: "1.0.0",
      contextPath: "/nova-test3",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-test-app4",
      dataSchemaVersion: "1.0.0",
      configSchemaVersion: "1.0.0",
      contextPath: "/nova-test4",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-workflow",
      dataSchemaVersion: "1.0.0",
      configSchemaVersion: "1.0.0",
      contextPath: "/nova-workflow",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-analytics",
      dataSchemaVersion: "1.0.0",
      configSchemaVersion: "1.0.0",
      contextPath: "/nova-analytics",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
  ],

  processData: {
    name: "Type Process Demo 4",
    description: "Demo process showing main and parallel phases from M0 → M8",
    documentationUrl: "https://example.com/",
    lifecycle: "PLAN",
  },
  milestones: [
    { name: "M0", description: "Project start" },
    { name: "M1", description: "Project initialization" },
    { name: "M2 Kick Off", description: "Kick-off milestone" },
    { name: "M3 QGC0", description: "Quality Gate 0" },
    { name: "QGC1", description: "Quality Gate 1" },
    { name: "QGC2", description: "Quality Gate 2" },
    { name: "M4-QGC3", description: "Quality Gate 3" },
    { name: "M5-QGC4", description: "Quality Gate 4" },
    { name: "M6-QGC5", description: "Quality Gate 5" },
    { name: "M7-QGC6", description: "Quality Gate 6" },
    { name: "M8-QGC7", description: "Quality Gate 7 / Project closure" },
  ],
  map: {
    "Project Initialization": ["M0", "M1"],
    "Planning and Kickoff": ["M1", "M2 Kick Off"],
    "Concept Design": ["M2 Kick Off", "M3 QGC0"],
    "Feasibility Review": ["M3 QGC0", "QGC1"],
    "Detailed Design": ["QGC1", "QGC2"],
    "Prototype Build": ["QGC2", "M4-QGC3"],
    "Prototype Build Parallel": ["QGC2", "M4-QGC3"],
    "Testing Preparation": ["M4-QGC3", "M5-QGC4"],
    Verification: ["M5-QGC4", "M6-QGC5"],
    Validation: ["M6-QGC5", "M7-QGC6"],
    "Final Release": ["M7-QGC6", "M8-QGC7"],
    "Concept Branch A": ["M2 Kick Off", "M3 QGC0"],
    "Concept Branch B": ["M2 Kick Off", "M3 QGC0"],
    "Feasibility Review B": ["M3 QGC0", "QGC1"],
    "Verification Track A": ["M5-QGC4", "M6-QGC5"],
    "Validation Track A": ["M6-QGC5", "M7-QGC6"],
    "Verification Track B": ["M5-QGC4", "M6-QGC5"],
    "Validation Track B": ["M6-QGC5", "M7-QGC6"],
  } as Record<string, [string, string]>,
  independentPhases: [],
  workPackages: [
    {
      id: "",
      name: "Work Package - Project Initialization",
      description: "Work package for Project Initialization",
      phaseId: "Project Initialization",
    },
    {
      id: "",
      name: "Work Package - Planning and Kickoff",
      description: "Work package for Planning and Kickoff",
      phaseId: "Planning and Kickoff",
    },
    {
      id: "",
      name: "Work Package - Concept Design",
      description: "Work package for Concept Design",
      phaseId: "Concept Design",
    },
    {
      id: "",
      name: "Work Package - Feasibility Review",
      description: "Work package for Feasibility Review",
      phaseId: "Feasibility Review",
    },
    {
      id: "",
      name: "Work Package - Detailed Design",
      description: "Work package for Detailed Design",
      phaseId: "Detailed Design",
    },
    {
      id: "",
      name: "Work Package - Prototype Build",
      description: "Work package for Prototype Build",
      phaseId: "Prototype Build",
    },
    {
      id: "",
      name: "Work Package - Prototype Build Parallel",
      description: "Work package for Prototype Build Parallel",
      phaseId: "Prototype Build Parallel",
    },
    {
      id: "",
      name: "Work Package - Testing Preparation",
      description: "Work package for Testing Preparation",
      phaseId: "Testing Preparation",
    },
    {
      id: "",
      name: "Work Package - Verification",
      description: "Work package for Verification",
      phaseId: "Verification",
    },
    {
      id: "",
      name: "Work Package - Validation",
      description: "Work package for Validation",
      phaseId: "Validation",
    },
    {
      id: "",
      name: "Work Package - Final Release",
      description: "Work package for Final Release",
      phaseId: "Final Release",
    },
    {
      id: "",
      name: "Work Package - Concept Branch A",
      description: "Work package for Concept Branch A",
      phaseId: "Concept Branch A",
    },
    {
      id: "",
      name: "Work Package - Concept Branch B",
      description: "Work package for Concept Branch B",
      phaseId: "Concept Branch B",
    },
    {
      id: "",
      name: "Work Package - Feasibility Review B",
      description: "Work package for Feasibility Review B",
      phaseId: "Feasibility Review B",
    },
    {
      id: "",
      name: "Work Package - Verification Track A",
      description: "Work package for Verification Track A",
      phaseId: "Verification Track A",
    },
    {
      id: "",
      name: "Work Package - Validation Track A",
      description: "Work package for Validation Track A",
      phaseId: "Validation Track A",
    },
    {
      id: "",
      name: "Work Package - Verification Track B",
      description: "Work package for Verification Track B",
      phaseId: "Verification Track B",
    },
    {
      id: "",
      name: "Work Package - Validation Track B",
      description: "Work package for Validation Track B",
      phaseId: "Validation Track B",
    },
  ],

  artifact: {
    files: [
      {
        name: "Artifact File",
        description: "Artifact File",
        type: "FILE",
        relativePath: "/apic",
      },
      {
        name: "Artifact File 1",
        description: "Artifact File 1",
        type: "FILE",
        relativePath: "/apic1",
      },
      {
        name: "Artifact Report",
        description: "Report file for documentation",
        type: "FILE",
        relativePath: "/report",
      },
      {
        name: "Artifact Diagram",
        description: "System diagram image",
        type: "FILE",
        relativePath: "/diagram",
      },
      {
        name: "Artifact Checklist",
        description: "Checklist file",
        type: "FILE",
        relativePath: "/checklist",
      },
    ],
    webForms: [
      {
        name: "nova-test-app1",
        description: "Description for nova-test-app1",
        type: "WEBFORM",
        pmAppConfiguration: {
          empty: true,
          additionalProp1: "string",
          additionalProp2: "string",
          additionalProp3: "string",
        },
        pmApp: "nova-test-app1",
      },
      {
        name: "nova-test-app2",
        description: "Description for nova-test-app2",
        type: "WEBFORM",
        pmAppConfiguration: {
          empty: true,
          additionalProp1: "string",
          additionalProp2: "string",
          additionalProp3: "string",
        },
        pmApp: "nova-test-app2",
      },
      {
        name: "nova-test-app3",
        description: "Description for nova-test-app3",
        type: "WEBFORM",
        pmAppConfiguration: {
          empty: true,
          additionalProp1: "string",
          additionalProp2: "string",
          additionalProp3: "string",
        },
        pmApp: "nova-test-app3",
      },
      {
        name: "nova-test-app4",
        description: "Description for nova-test-app4",
        type: "WEBFORM",
        pmAppConfiguration: {
          empty: true,
          additionalProp1: "string",
          additionalProp2: "string",
          additionalProp3: "string",
        },
        pmApp: "nova-test-app4",
      },
      {
        name: "nova-workflow",
        description: "Workflow PM App",
        type: "WEBFORM",
        pmAppConfiguration: {
          empty: true,
          additionalProp1: "string",
          additionalProp2: "string",
          additionalProp3: "string",
        },
        pmApp: "nova-workflow",
      },
      {
        name: "nova-analytics",
        description: "Analytics PM App",
        type: "WEBFORM",
        pmAppConfiguration: {
          empty: true,
          additionalProp1: "string",
          additionalProp2: "string",
          additionalProp3: "string",
        },
        pmApp: "nova-analytics",
      },
    ],
  },
  activities: [
    {
      name: "Activity 1",
      description: "Description for Activity 1",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-test-app1", "Artifact File 1"],
      outputArtifacts: ["Artifact File", "nova-test-app2"],
      workPackageId: "Work Package - Project Initialization",
      phaseId: "Project Initialization",
    },

    {
      name: "Collect Requirements",
      description: "Gather initial requirements",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-test-app1"],
      outputArtifacts: ["Artifact File"],
      workPackageId: "Work Package - Planning and Kickoff",
      phaseId: "Planning and Kickoff",
    },

    {
      name: "Initial Concept Draft",
      description: "Create early concept draft",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File"],
      outputArtifacts: ["nova-test-app2"],
      workPackageId: "Work Package - Concept Design",
      phaseId: "Concept Design",
    },

    {
      name: "Feasibility Assessment",
      description: "Evaluate feasibility constraints",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File 1"],
      outputArtifacts: ["Artifact File"],
      workPackageId: "Work Package - Feasibility Review",
      phaseId: "Feasibility Review",
    },

    {
      name: "Detail Technical Specification",
      description: "Prepare detailed specifications",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-test-app2"],
      outputArtifacts: ["Artifact File 1"],
      workPackageId: "Work Package - Detailed Design",
      phaseId: "Detailed Design",
    },

    {
      name: "Prototype Assembly",
      description: "Build initial prototype",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File", "nova-test-app1"],
      outputArtifacts: ["Artifact File 1"],
      workPackageId: "Work Package - Prototype Build",
      phaseId: "Prototype Build",
    },

    {
      name: "Prototype Assembly Parallel",
      description: "Parallel prototype construction",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File"],
      outputArtifacts: ["nova-test-app2"],
      workPackageId: "Work Package - Prototype Build Parallel",
      phaseId: "Prototype Build Parallel",
    },

    {
      name: "Testing Preparation Setup",
      description: "Prepare test environment",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File 1"],
      outputArtifacts: ["Artifact File"],
      workPackageId: "Work Package - Testing Preparation",
      phaseId: "Testing Preparation",
    },

    {
      name: "Verification Execution",
      description: "Execute verification procedures",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File"],
      outputArtifacts: ["nova-test-app1"],
      workPackageId: "Work Package - Verification",
      phaseId: "Verification",
    },

    {
      name: "Validation Execution",
      description: "Execute validation procedures",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File"],
      outputArtifacts: ["Artifact File 1"],
      workPackageId: "Work Package - Validation",
      phaseId: "Validation",
    },

    {
      name: "Final Release Documentation",
      description: "Prepare release documentation",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-test-app1"],
      outputArtifacts: ["nova-test-app2"],
      workPackageId: "Work Package - Final Release",
      phaseId: "Final Release",
    },

    {
      name: "Concept Branch A Review",
      description: "Review alternative concept A",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File"],
      outputArtifacts: ["Artifact File 1"],
      workPackageId: "Work Package - Concept Branch A",
      phaseId: "Concept Branch A",
    },

    {
      name: "Concept Branch B Review",
      description: "Review alternative concept B",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-test-app2"],
      outputArtifacts: ["nova-test-app1"],
      workPackageId: "Work Package - Concept Branch B",
      phaseId: "Concept Branch B",
    },

    {
      name: "Feasibility Review B Analysis",
      description: "Deep analysis for Feasibility Review B",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File 1"],
      outputArtifacts: ["Artifact File"],
      workPackageId: "Work Package - Feasibility Review B",
      phaseId: "Feasibility Review B",
    },

    {
      name: "Verification Track A Execution",
      description: "Perform verification in track A",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-test-app1"],
      outputArtifacts: ["Artifact File 1"],
      workPackageId: "Work Package - Verification Track A",
      phaseId: "Verification Track A",
    },

    {
      name: "Validation Track A Execution",
      description: "Perform validation in track A",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File 1"],
      outputArtifacts: ["Artifact File"],
      workPackageId: "Work Package - Validation Track A",
      phaseId: "Validation Track A",
    },

    {
      name: "Verification Track B Execution",
      description: "Perform verification in track B",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Artifact File"],
      outputArtifacts: ["Artifact File 1"],
      workPackageId: "Work Package - Verification Track B",
      phaseId: "Verification Track B",
    },

    {
      name: "Validation Track B Execution",
      description: "Perform validation in track B",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-test-app2"],
      outputArtifacts: ["Artifact File"],
      workPackageId: "Work Package - Validation Track B",
      phaseId: "Validation Track B",
    },
  ],
};
