export const PROCESS_LCM3 = {
  processData: {
    name: "Type Process Demo 3",
    description: "Demo process showing main and parallel phases from M0 → M8",
    documentationUrl: "https://example.com/",
    lifecycle: "PLAN",
  },
  milestones: [
    { name: "M0", description: "Project start" },
    { name: "M1", description: "Project initialization" },
    { name: "M2 Kick Off", description: "Kick-off milestone" },
    { name: "M3 QGC0", description: "Quality Gate 0" },
    { name: "QGC1", description: "Quality Gate 1" },
    { name: "QGC2", description: "Quality Gate 2" },
    { name: "M4-QGC3", description: "Quality Gate 3" },
    { name: "M5-QGC4", description: "Quality Gate 4" },
    { name: "M6-QGC5", description: "Quality Gate 5" },
    { name: "M7-QGC6", description: "Quality Gate 6" },
    { name: "M8-QGC7", description: "Quality Gate 7 / Project closure" },
  ],
  map: {
    "Project Initialization": ["M0", "M1"],
    "Planning and Kickoff": ["M1", "M2 Kick Off"],
    "Concept Design": ["M2 Kick Off", "M3 QGC0"],
    "Feasibility Review": ["M3 QGC0", "QGC1"],
    "Detailed Design": ["QGC1", "QGC2"],
    "Prototype Build": ["QGC2", "M4-QGC3"],
    "Testing Preparation": ["M4-QGC3", "M5-QGC4"],
    Verification: ["M5-QGC4", "M6-QGC5"],
    Validation: ["M6-QGC5", "M7-QGC6"],
    "Final Release": ["M7-QGC6", "M8-QGC7"],
    "Concept Branch A": ["M2 Kick Off", "M3 QGC0"],
    "Concept Branch B": ["M2 Kick Off", "M3 QGC0"],
    "Feasibility Review B": ["M3 QGC0", "QGC1"],
    "Verification Track A": ["M5-QGC4", "M6-QGC5"],
    "Validation Track A": ["M6-QGC5", "M7-QGC6"],
    "Verification Track B": ["M5-QGC4", "M6-QGC5"],
    "Validation Track B": ["M6-QGC5", "M7-QGC6"],
  } as Record<string, [string, string]>,
  independentPhases: [],
};
