export const PROCESS_LCM5 = {
  novaApps: [
    {
      name: "nova-req",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-design",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-build",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-test",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-release",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-ops",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-risk",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-sec",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-data",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
    {
      name: "nova-portfolio",
      dataSchemaVersion: "2.0.0",
      configSchemaVersion: "2.0.0",
      createdBy: null,
      modifiedBy: null,
      createdAt: null,
      modifiedAt: null,
    },
  ],
  processData: {
    name: "Enterprise Program LCM",
    description:
      "Large-scale lifecycle with main waves, parallel tracks, and governance gates G0 → G12",
    documentationUrl: "https://example.com/enterprise-lcm",
    lifecycle: "LIVE",
  },
  milestones: [
    { name: "G0 Charter", description: "Program charter approved" },
    { name: "G1 Scope Freeze", description: "Scope and OKRs finalized" },
    {
      name: "G2 Architecture Approved",
      description: "Target architecture signed off",
    },
    { name: "G3 Build Start", description: "Engineering build starts" },
    { name: "G4 SIT Entry", description: "System Integration Test entry" },
    { name: "G5 SIT Exit", description: "System Integration Test exit" },
    { name: "G6 UAT Entry", description: "User Acceptance Test entry" },
    { name: "G7 UAT Exit", description: "User Acceptance Test exit" },
    { name: "G8 Reg Approval", description: "Regulatory approval granted" },
    {
      name: "G9 Go-Live Readiness",
      description: "Go-live readiness confirmed",
    },
    { name: "G10 Go-Live", description: "Production go-live" },
    { name: "G11 Hypercare Complete", description: "Stabilization complete" },
    { name: "G12 Closure", description: "Program closed and archived" },
  ],

  map: {
    Initiation: ["G0 Charter", "G1 Scope Freeze"],
    "Strategy & Scoping": ["G0 Charter", "G1 Scope Freeze"],
    "Enterprise Architecture": ["G1 Scope Freeze", "G2 Architecture Approved"],
    "Implementation Wave 1": ["G2 Architecture Approved", "G3 Build Start"],
    "Implementation Wave 2": ["G3 Build Start", "G4 SIT Entry"],
    "Data Migration": ["G3 Build Start", "G4 SIT Entry"],
    "System Integration": ["G4 SIT Entry", "G5 SIT Exit"],
    "Performance & Hardening": ["G5 SIT Exit", "G6 UAT Entry"],
    UAT: ["G6 UAT Entry", "G7 UAT Exit"],
    "Regulatory Review": ["G7 UAT Exit", "G8 Reg Approval"],
    "Go-Live Prep": ["G8 Reg Approval", "G9 Go-Live Readiness"],
    "Go-Live": ["G9 Go-Live Readiness", "G10 Go-Live"],
    Hypercare: ["G10 Go-Live", "G11 Hypercare Complete"],
    "Operational Handover": ["G11 Hypercare Complete", "G12 Closure"],
    // Parallel/Tracks
    "Security Hardening Parallel": ["G5 SIT Exit", "G6 UAT Entry"],
    "Data Cleansing Parallel": ["G3 Build Start", "G4 SIT Entry"],
    "Integration Track A": ["G4 SIT Entry", "G5 SIT Exit"],
    "Integration Track B": ["G4 SIT Entry", "G5 SIT Exit"],
    "Migration Track A": ["G3 Build Start", "G4 SIT Entry"],
    "Migration Track B": ["G3 Build Start", "G4 SIT Entry"],
  } as Record<string, [string, string]>,

  independentPhases: [],

  workPackages: [
    {
      id: "",
      name: "WP - Initiation",
      description: "Initiation activities",
      phaseId: "Initiation",
    },
    {
      id: "",
      name: "WP - Strategy & Scoping",
      description: "Strategy and scoping",
      phaseId: "Strategy & Scoping",
    },
    {
      id: "",
      name: "WP - Enterprise Architecture",
      description: "Architecture definition",
      phaseId: "Enterprise Architecture",
    },
    {
      id: "",
      name: "WP - Implementation Wave 1",
      description: "First build wave",
      phaseId: "Implementation Wave 1",
    },
    {
      id: "",
      name: "WP - Implementation Wave 2",
      description: "Second build wave",
      phaseId: "Implementation Wave 2",
    },
    {
      id: "",
      name: "WP - Data Migration",
      description: "Data migration planning & exec",
      phaseId: "Data Migration",
    },
    {
      id: "",
      name: "WP - System Integration",
      description: "SIT execution",
      phaseId: "System Integration",
    },
    {
      id: "",
      name: "WP - Performance & Hardening",
      description: "Perf tests & hardening",
      phaseId: "Performance & Hardening",
    },
    {
      id: "",
      name: "WP - UAT",
      description: "User acceptance testing",
      phaseId: "UAT",
    },
    {
      id: "",
      name: "WP - Regulatory Review",
      description: "Regulatory approvals",
      phaseId: "Regulatory Review",
    },
    {
      id: "",
      name: "WP - Go-Live Prep",
      description: "Cutover prep",
      phaseId: "Go-Live Prep",
    },
    {
      id: "",
      name: "WP - Go-Live",
      description: "Cutover & deploy",
      phaseId: "Go-Live",
    },
    {
      id: "",
      name: "WP - Hypercare",
      description: "Stabilization",
      phaseId: "Hypercare",
    },
    {
      id: "",
      name: "WP - Operational Handover",
      description: "Handover to Ops",
      phaseId: "Operational Handover",
    },
    // Parallel
    {
      id: "",
      name: "WP - Security Hardening Parallel",
      description: "Security stream",
      phaseId: "Security Hardening Parallel",
    },
    {
      id: "",
      name: "WP - Data Cleansing Parallel",
      description: "Data cleansing stream",
      phaseId: "Data Cleansing Parallel",
    },
    {
      id: "",
      name: "WP - Integration Track A",
      description: "Integration A",
      phaseId: "Integration Track A",
    },
    {
      id: "",
      name: "WP - Integration Track B",
      description: "Integration B",
      phaseId: "Integration Track B",
    },
    {
      id: "",
      name: "WP - Migration Track A",
      description: "Migration A",
      phaseId: "Migration Track A",
    },
    {
      id: "",
      name: "WP - Migration Track B",
      description: "Migration B",
      phaseId: "Migration Track B",
    },
  ],

  artifact: {
    files: [
      {
        name: "BRD",
        description: "Business Requirements Document",
        type: "FILE",
        relativePath: "/docs/brd",
      },
      {
        name: "SolutionBlueprint",
        description: "Solution blueprint",
        type: "FILE",
        relativePath: "/docs/blueprint",
      },
      {
        name: "TestPlan",
        description: "Master test plan",
        type: "FILE",
        relativePath: "/docs/test-plan",
      },
      {
        name: "Runbook",
        description: "Ops runbook",
        type: "FILE",
        relativePath: "/docs/runbook",
      },
      {
        name: "MigrationPlan",
        description: "Data migration plan",
        type: "FILE",
        relativePath: "/docs/migration-plan",
      },
      {
        name: "InterfaceSpec",
        description: "Interface specifications",
        type: "FILE",
        relativePath: "/docs/interfaces",
      },
      {
        name: "SecurityChecklist",
        description: "Security checklist",
        type: "FILE",
        relativePath: "/docs/security-checklist",
      },
      {
        name: "OpsManual",
        description: "Operations manual",
        type: "FILE",
        relativePath: "/docs/ops-manual",
      },
      {
        name: "ReleaseNotes",
        description: "Release notes",
        type: "FILE",
        relativePath: "/docs/release-notes",
      },
    ],
    webForms: [
      {
        name: "nova-req",
        description: "Requirements intake form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-req",
      },
      {
        name: "nova-design",
        description: "Design review form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-design",
      },
      {
        name: "nova-build",
        description: "Build progress form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-build",
      },
      {
        name: "nova-test",
        description: "Test execution form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-test",
      },
      {
        name: "nova-release",
        description: "Release readiness form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-release",
      },
      {
        name: "nova-ops",
        description: "Operations checklist form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-ops",
      },
      {
        name: "nova-risk",
        description: "Risk log form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-risk",
      },
      {
        name: "nova-sec",
        description: "Security assessment form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-sec",
      },
      {
        name: "nova-data",
        description: "Data migration form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-data",
      },
      {
        name: "nova-portfolio",
        description: "Portfolio status form",
        type: "WEBFORM",
        appConfiguration: { empty: true },
        novaApp: "nova-portfolio",
      },
    ],
  },

  activities: [
    {
      name: "Charter Finalization",
      description: "Finalize program charter and objectives",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-portfolio"],
      outputArtifacts: ["BRD"],
      workPackageId: "WP - Initiation",
      phaseId: "Initiation",
    },
    {
      name: "Scope & OKR Definition",
      description: "Define scope, OKRs, and KPIs",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["BRD", "nova-req"],
      outputArtifacts: ["SolutionBlueprint"],
      workPackageId: "WP - Strategy & Scoping",
      phaseId: "Strategy & Scoping",
    },
    {
      name: "Architecture Review Board",
      description: "ARB approval for target state",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["SolutionBlueprint", "SecurityChecklist"],
      outputArtifacts: ["InterfaceSpec"],
      workPackageId: "WP - Enterprise Architecture",
      phaseId: "Enterprise Architecture",
    },
    {
      name: "Build Wave 1 Setup",
      description: "Stand up build toolchain and repos",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["InterfaceSpec", "nova-build"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Implementation Wave 1",
      phaseId: "Implementation Wave 1",
    },
    {
      name: "Build Wave 2 Feature Dev",
      description: "Develop prioritized features",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["ReleaseNotes", "nova-design"],
      outputArtifacts: ["InterfaceSpec"],
      workPackageId: "WP - Implementation Wave 2",
      phaseId: "Implementation Wave 2",
    },
    {
      name: "Data Mapping Definition",
      description: "Define mappings and transformations",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["BRD", "nova-data"],
      outputArtifacts: ["MigrationPlan"],
      workPackageId: "WP - Data Migration",
      phaseId: "Data Migration",
    },
    {
      name: "Cleansing Parallel Run",
      description: "Execute data cleansing in parallel",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["MigrationPlan", "nova-data"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Data Cleansing Parallel",
      phaseId: "Data Cleansing Parallel",
    },
    {
      name: "SIT Environment Prep",
      description: "Prepare SIT env with integrations",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["InterfaceSpec", "nova-test"],
      outputArtifacts: ["TestPlan"],
      workPackageId: "WP - System Integration",
      phaseId: "System Integration",
    },
    {
      name: "Integration Execution A",
      description: "Run integration scenarios for Track A",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["TestPlan", "nova-test"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Integration Track A",
      phaseId: "Integration Track A",
    },
    {
      name: "Integration Execution B",
      description: "Run integration scenarios for Track B",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["TestPlan", "nova-test"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Integration Track B",
      phaseId: "Integration Track B",
    },
    {
      name: "Security Hardening",
      description: "Remediate high-risk findings",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["SecurityChecklist", "nova-sec"],
      outputArtifacts: ["Runbook"],
      workPackageId: "WP - Security Hardening Parallel",
      phaseId: "Security Hardening Parallel",
    },
    {
      name: "Performance Tuning",
      description: "Execute perf tests and tune",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["TestPlan", "nova-build"],
      outputArtifacts: ["Runbook"],
      workPackageId: "WP - Performance & Hardening",
      phaseId: "Performance & Hardening",
    },
    {
      name: "UAT Planning",
      description: "Plan UAT cycles and scripts",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["BRD", "TestPlan", "nova-req"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - UAT",
      phaseId: "UAT",
    },
    {
      name: "UAT Execution",
      description: "Execute UAT and track defects",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["ReleaseNotes", "nova-test"],
      outputArtifacts: ["OpsManual"],
      workPackageId: "WP - UAT",
      phaseId: "UAT",
    },
    {
      name: "Regulatory Submission",
      description: "Submit package to regulator",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["OpsManual", "Runbook", "nova-risk"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Regulatory Review",
      phaseId: "Regulatory Review",
    },
    {
      name: "Risk Acceptance",
      description: "Formalize residual risk acceptance",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["nova-risk", "SecurityChecklist"],
      outputArtifacts: ["Runbook"],
      workPackageId: "WP - Regulatory Review",
      phaseId: "Regulatory Review",
    },
    {
      name: "Cutover Rehearsal",
      description: "Run dress rehearsal",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Runbook", "MigrationPlan"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Go-Live Prep",
      phaseId: "Go-Live Prep",
    },
    {
      name: "Go/No-Go",
      description: "Final readiness review",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["ReleaseNotes", "nova-release"],
      outputArtifacts: ["Runbook"],
      workPackageId: "WP - Go-Live Prep",
      phaseId: "Go-Live Prep",
    },
    {
      name: "Production Cutover",
      description: "Execute cutover plan",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["Runbook", "nova-release"],
      outputArtifacts: ["OpsManual"],
      workPackageId: "WP - Go-Live",
      phaseId: "Go-Live",
    },
    {
      name: "Hypercare Monitoring",
      description: "Stabilize and monitor KPIs",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["OpsManual", "nova-ops"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Hypercare",
      phaseId: "Hypercare",
    },
    {
      name: "Operational Readiness",
      description: "Validate ops readiness",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["OpsManual", "Runbook", "nova-ops"],
      outputArtifacts: ["OpsManual"],
      workPackageId: "WP - Operational Handover",
      phaseId: "Operational Handover",
    },
    {
      name: "Program Closure Report",
      description: "Finalize closure and archive",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["ReleaseNotes", "nova-portfolio"],
      outputArtifacts: ["BRD"],
      workPackageId: "WP - Operational Handover",
      phaseId: "Operational Handover",
    },
    // Migration Tracks
    {
      name: "Migration Load A",
      description: "Execute migration path A",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["MigrationPlan", "nova-data"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Migration Track A",
      phaseId: "Migration Track A",
    },
    {
      name: "Migration Load B",
      description: "Execute migration path B",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["MigrationPlan", "nova-data"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - Migration Track B",
      phaseId: "Migration Track B",
    },
    // Extra activities to enrich dataset
    {
      name: "Design Authority Sync",
      description: "Weekly DA sync to control design drift",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["SolutionBlueprint", "nova-design"],
      outputArtifacts: ["InterfaceSpec"],
      workPackageId: "WP - Enterprise Architecture",
      phaseId: "Enterprise Architecture",
    },
    {
      name: "Defect Triage Board",
      description: "Cross-functional triage cadence",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["TestPlan", "nova-test"],
      outputArtifacts: ["ReleaseNotes"],
      workPackageId: "WP - System Integration",
      phaseId: "System Integration",
    },
    {
      name: "Threat Modeling Workshop",
      description: "Threat model high-risk components",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["SecurityChecklist", "nova-sec"],
      outputArtifacts: ["Runbook"],
      workPackageId: "WP - Security Hardening Parallel",
      phaseId: "Security Hardening Parallel",
    },
    {
      name: "Ops KT Sessions",
      description: "Knowledge transfer to operations",
      responsibleRole: null,
      supportingRoles: [],
      inputArtifacts: ["OpsManual", "Runbook", "nova-ops"],
      outputArtifacts: ["OpsManual"],
      workPackageId: "WP - Operational Handover",
      phaseId: "Operational Handover",
    },
  ],
} as const;
